authorname: "Tim Gummer"
draft: false
engine: knitr 

project:
  type: website
  output-dir: _site_rendered
  
  
  resources:
    - "img/**"
    - "blog/2023/over-analysing-idle-footy-chat/longest-distance.jpg"

  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

title-meta: "Tim Gummer"
description-meta: "Associate Actuary (AIAA) | R Enthusiast"

# Enable banner style title blocks
title-block-banner: "#4C4C4B"

website:
  title: "Tim Gummer"
  description: "Associate Actuary (AIAA) | R Enthusiast"
  site-url: https://t-gummer.netlify.app
  
  repo-url: "https://github.com/t-gummer/t-gummer.netlify.app"
  repo-branch: master
  
  google-analytics: "G-V8P5XXLZK4"
  
  back-to-top-navigation: true
  reader-mode: false
  repo-actions: [edit, issue]
  
  search:
    location: navbar
    type: textbox
    
  navbar:
    pinned: true
    left:
      - text: Blog
        icon: newspaper
        href: blog/index.qmd
      - text: Goals
        icon: fingerprint
        href: goals/index.qmd    
      - text: CV
        icon: file-earmark-person
        href: cv/index.qmd    
    right:
      - icon: github
        href: https://github.com/t-gummer
      - icon: linkedin
        href: https://www.linkedin.com/in/timothy-gummer/
      - icon: envelope
        aria-label: email
        href: "mailto:mail.timothy.gummer@gmail.com"
    
  page-footer: 
    left: |
      <span class="faux-block">{{< fa regular copyright >}} 2023 Tim Gummer</span>
      <span class="faux-block"><a href="https://github.com/t-gummer/t-gummer.netlify.app" target="_blank">{{< fa brands github >}} Source Code</a></span>
    center: |
      <span class="faux-block light-mode">Click the <a href = "" class = "" onclick="window.quartoToggleColorScheme(); return false;" title="Initiate hacker mode!"><i class="fa-solid fa-toggle-off"></i></a> icon in the navigation bar</span>
      <span class="faux-block light-mode"> to initiate dark (hacker) mode 😁</span>
      <span class="faux-block dark-mode">Click the <a href = "" class = "" onclick="window.quartoToggleColorScheme(); return false;" title="Return to normie mode?"><i class="fa-solid fa-toggle-on"></i></a> icon  in the navigation bar</span>
      <span class="faux-block dark-mode"> to return to light (normie) mode 😞</span>
    right: |
      <span class="faux-block"> Designed with {{< fa heart >}} using</span>
      <span class="faux-block"> <a href="https://www.r-project.org" target="_blank">{{< fa brands r-project >}}</a> and <a href="https://quarto.org" target="_blank">Quarto</a></span>

execute:
  freeze: true    

format:
  html:
    fontsize: 1.1em
    code-link: true
    page-layout: full # https://quarto.org/docs/output-formats/page-layout.html
    grid:
      body-width:	1000px
    theme:
      light: [www/styles.scss, www/tgLight.scss] # flatly
      dark: [www/styles.scss, www/tgHacker.scss] # www/styles.scss, darkly
    toc: true
    toc-location: left
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
    highlight-style: monokai
    
editor: source