---
title: "Responses to '`blogging.txt`'"
description: |
  This is a response to a rather lengthy feedback I have received.
date: 2023-08-13
categories: 
  - bad
image: bt.jfif
reference-location: margin
draft: false
freeze: false
reading-time: true
---

# `blogging.txt`

> brought to you by: [https://ianwilliamcraig.bandcamp.com/album/a-forgetting-place](https://ianwilliamcraig.bandcamp.com/album/a-forgetting-place){target="_blank"}

Duly noted will give it a listen

## blog page
  
> do not write "welcome to my blog" on your blog

> verbose? hardly

> generalities:
  toggling reader mode (on desktop) simply collapses (and enables the ability to expand/collapse) the contents tab on the left. if it were to flatten formatting and widen the bounding box to use more screen real estate (as reader modes typically do) as it stands the feature is pointless and likely a stock bit of a package added as a "why not"

> comments section is both not on the contents tab and requires a sign in from a different website, though likely one your readership is likely to have. this is a recipe for 0 feedback. i would have liked to post this entire text document publically and anonymously, and was denied this pleasure. rectify this.

> text used for hyperlinks is not indexed in the search bar (search "boffins" to check this), neither is text in footnotes (search "gadget")

> conversational tone taken throughout has divested your good sense on where to place commas, this will make up the bulk of adjustments. writing style leaves something to be desired but will endeavour to avoid correcting this, we know you have your ways. most of the comma-based corrections will place the comma inside the example text, while wording corrections will explain their placement outside the quotation to preserve easy ctrl-f-ing

> though this article has been out for a couple of weeks, it'd be good if you could implement at least some of these changes while it is the only one present on your website. unfortunately, you only get one chance at a first impression, and that time is long past. judging by the views on the BT clip you shared, this article was read (or shared with) by about 10 people, 11 including me. i believe greater readership is possible.

## article proper

> adjust the tone of the foreword marked "apologies for the delay" from apologetic to those who you have promised this work, to informing/warning the prospective reader of your particular idiosyncracies (if it is to be preserved at all). starting your first ever post with an apology for (not) writing it (well enough) is rarely a winning strategy. easiest way to do this is simply remove the heading and first two lines and simply call this a mission statement or reflection or examen or whatever you like. perhaps place it at the end of the article too.

> "I often have all the ideas in my head, but when it comes to putting them into nice, publishable words, it becomes a bit of a slog." add comma + becomes. consider rewriting this. "nice, publishable words" is good but should be slotted into a better sentence

> "I commend anyone who actually reads the whole thing, but hopefully it's also possible to jump around and only read the parts that interest you in particular using the table of contents." added comma + it's ("it's" is short for "it is" whereas "its" is possessive, think about it in terms of the words "he's" vs. "his" rather than the proper nouns that cause this confusion ("Tim's" is not short for "Tim is"))

> "1 As a Western Australian this is how I define it (along with the majority of Australia) but I am aware that this term is reserved for rugby league in New South Wales and Queensland" footnotes in articles by convention are short and to the point and are typically used for references, if you have much to say it ought to be in the main body of the article or removed entirely. amend this for brevity and more earnest cruelty for easterners.

> ""the most data rich sport on Earth"2," should be a hyperlink

> "But what are us plebeians meant to do, bereft of such luxuries you might ask?" why is this quoted? remove the quotation formatting or "you might ask" from the end of this

> "The more savvy among us may find answers to slightly more edifying questions by performing pro gamer moves such as:" end with a colon or emdash (lol) to avoid colonspam, also too many qualifiers in one sentence, remove either "may" or "slightly", what this article needs is a strong leader

> ""What is the most disposals Zac Dawson had in a game"7;" text within quotation marks should start capitalised, and added an s to "disposals"

> ""what is the record for the longest distance run in a game".8" same as previous, also footnote should be hyperlinked for parity with previous, if possible. add a full stop too.

> "but some questions will still go unanswered." this should be a new sentence, reading something like "Even so, the most complex questions will still go unanswered."

> would like to see some text early on framing the article more directly attempting to place this outlier of a game into the context of the full history of afl stats. from reading the whole thing this is obvious but it would be good to have that formalised early on, as well as the term "infamous game" used throughout to refer to the syd vs. wce game. add this in either the question list or concrete example sections

> "However, if you are a gadget-type operator9 like myself," style guides will tell you to never start a sentence with "however", these style guides are irrelevant nonsense. you do need a comma though

> "9 My footy tipping username is Gadget-type Operator and I often use other BT quotes for my username on other (even non-footy-related) accounts" hyperlinked the same video in both BT referencing footnotes

> "There are, of course, a multitude of tools and approaches to this, but in this post, I will be using R (my preferred programming language)." commas, for flavour

> "Target Audience Unclear" you said it fella. this section is quoted erroneously, and should probably should be put in place of/be incorporated into the "apologies for the delay" section

> "If we also consider that my usual footy-going companion (Saroop) and I are both actuaries by trade, it is safe to say that footy stats questions were flying left, right and centre on that gloomy (but not because of the weather) Saturday night at the SCG. The questions we posed did not just vanish into the aether either, I (with the idea of writing this article in mind) decided to record the more interesting (and doable) questions" some stylistic and readability suggestions - remove "if we also consider that" and replace with "as", add "as pictured" or "pictured, right" to (Saroop), add an oxford comma to "left, right, and centre", remove "it is safe to say that" and replace with "the", replace "but not because of" with "though not due to", remove the brackets around (with the idea of writing...) and add a comma beforehand instead, good usage of the archaic form of "aether", no change

> "Disclaimer on the asterisk" section entirely defeats the point of an asterisk, place the explanation in the side panel with the footnotes (significantly shortened), or it its current position (slightly shortened), whatever you choose to do, the line "I have put an asterisk next to..." must be removed.

> "The first step in analysing AFL data is obtaining the data (the so-called "collection" phase). Our first thought..." repetition of the word "first" here is inadvisable, try "Before any analysis can take place, we must obtain the data we wish to work with" etc. etc. as you have begun the technical phase of the article you have taken on the tone of a tutorial rather than a conversation as previously, perhaps unconsiously, as if you expect the prospective reader to follow along. this is fine but should be done carefully and consistently, have a reread of these sections yourself to ensure this tone is maintained throughout sections where it ought to (we and our instead of i and my for example)

> "10 It is also (regrettably) the place of my birth but as a WA boy I don't like to talk about the fact that my parents happened to be in Melbourne when I was born." weird footnote just get rid of it

> would like to note that i was the 1000th view on the fitzroy lions anthem video

> "fitzRoy R package" add a hyperlink to the documentation to the first usage of this and include the author/group's name in that line

> "fitzRoy provides access to a number of footy data sources11..." could also be a hyperlink

> "12 Centre bounce attendances (CBAs) are a commonly-used metrics in AFL fantasy, coaches often look at tools such as this one to help with researching their trades." remove s from "metrics", change "coaches" to more generic terminology like "participants" (not participants specifically, that's rubbish) or add the prefix "fantasy" to ensure such people are not confused with real actual coaches, no, i don't care that the word before the comma is "fantasy", you're ostensibly writing this for data autists, footy fans or both, and only the both group will know implicitly what you mean. best rule of article writing is to assume your audience is retarded while constantly reassuring them that they're hugely intelligent for being able to comprehend what you're saying, they'll never notice the condescension

> "Data Sources Table" - stick with me here:
> 
> {
>     
> clicking a column to sort the table twice should return the table to its original, unsorted state. currently there is no way to do this other than to refresh the page. paradoxically, the table is sorted in what appears to be a random order (almost certainly the order in which the data was entered into the table) and should instead be organised by one of the metrics of the columns by default (probably the data sources alphabetically). the first of these doesn't actually matter and just annoys me, so implementing just the second should be enough
> 
> when expanding the rows in the data source column, an extra row expands, granting further detail on what data the fitzRoy package calls. my question is, what is the "unqiue" column? why does it ruin the symmetry and cleanliness of this otherwise lovely table? the addition of a thick, ugly slide bar to 2 out of 5 rows is not worth the additional links, which could easily be footnotes or ommitted? why is "unique" misspelt?
> 
> row "Squiggle", column "Speed of Fetch" rollover pop-up text: "indended to be slow" - was this indendional?
> 
> add some commas to the rollover pop-up text of the "AFL Tables" and "Footywire" rows in the "Level of Detail" column
> 
> }


> "When sourcing data from fitzRoy, it is important to follow good data collection14 etiquette..." another hyperlink

> opportunity

> "...I use readRDS()." put this in brackets, or explain it more in a footnote (why? what is it? why should i care?), or get rid of it. probably the first one. also it's a hyperlink, but isn't orange? more on that later

> "16 Note that I have not written a base R dataframes version because I can see arguments for using both tidyverse and data.table but base R data.frames will probably cause more pain than they are worth (there is a reason that tidyverse and data.table exist)" added a comma, while this is already an unwieldy footnote, you have alluded to a third, inferior method to achieve your goals without explaining how it is inferior. should make it snappier or remove it, could change this sentence to something like "16 could also write this as a base r dataframes version, but trust me, it's not worth it"

> more general advice than specific but there's a lot of "I have" and "I will" from this point forward. could shift some words around to feel less diaristic and repetitive

> "However this is add the _tb suffix18 to distinguish it from the data.table code." i do not believe you had a proofreader besides me

> "The so-called pipe operator (%> %) of the magrittr package has been a core staple of tidyverse since its inception, but since the R core team introduced the so-called native pipe (|> ) to base R (in version 4.120), this has led to a split in adoption." added comma

> "20 another cool thing introduced in this version of R was so-called function shorthand (\()), see help("function") for more details" hyperlink in this footnote is not orange. need more formatting consistency. if you'd like to check your hyperlinks in future, easy way to do this is create a blank bookmark in chrome and paste this bit of javascript in as the URL (or write your own, since you can do that): javascript:(function(){for(i=0;i<document.links.length;i++)document.links[i].style.backgroundColor='#ffff00';})();

> "Note that the common RStudio shortcut, Ctrl+Shift+M can be changed from the magrittr pipe (%> %), which is still the default, to the native pipe (|> )." why is this quoted?
  
  > the "webscraping package" section could be put with the fitzRoy section, no reason to bury the lede, 'specially since you've got a hyperlink back to that section in this one anyway

> you like "note that" rather a lot. not a criticism, merely an observation

> latter sections are largely above my head to critique and also significantly more confidently written as you're finally in what must be familiar territory. there will be large gaps between issues from this point on.

> in the "flattening the data" section, the second tabbed portion with tabs marked "tidyverse" and "data.table" there's a captioning line below both code outputs marked "[1] TRUE" what is this and what does it mean

> "Now lets use these functions23 to add a primary key to our match_stats_flat_* datasets." let's vs. lets

> the tabs in the "player URLs" section have the same problem as the "flattening the data" section's tabs, but only in the data.table tab this time? must surely be an error. henceforth, errors of this type will be marked with "1TRUE"

> the tabs detailing the code for filtering the match stats data should be under the subheading of match stats, mirroring the player stats section. consistency!
  
  > in the "match stats" and "player stats" sections, the outputted tables are horrific to behold. look at those sliders? the player stats one can barely be displayed and needs TEN (10) numerically notarised pages, each displaying five of forty six rows? the unedited variable names for column labels? bursting at the seams they are. these appear automatically generated and really should not be tables at all. though i understand the wish to avoid tabspam, it would be advisable to put them in the spreadsheet-esque format and hide the output in tabs as you did earlier in the document for readability's sake at the very least

> "Not that there is already a page on this topic on AFL Tables, but it is a good one to start with regardless." "Note", not "Not". also it was very kind of you to avoid "irregardless"

> you probably don't need to hyperlink back to the questions every time you mention them, wikipedia only does it for the first usage so why shouldn't you

> another bit of general advice that will need fixing in almost all cases, table column headings are frequently too small to display their labels pleasantly, good example is every usage of "opposition" in a table has just the "n" on a new line. very nasty. additionally table headings are wrapped to either the left or right of their bounding boxes, appearing to be entirely at random. tables need to be individually wrangled with for aesthetics whenever they are used, since aesthetics is readability and readability is everything. good reason not to use them

> "highest scoring quarter" section, first tabs 1TRUE

> "first quarter" section, 1TRUE

> "The record for the highest-scoring first quarter occurred during the bloodbath of an encounter that was the Bombers' first ever clash with the Gary Ablett Junior-led Gold Coast Suns in their inaugural season in the AFL." "Junior" to "Jr.", i understand the temptation to not double up on punctuation but really the full word junior should never be written. could add a comma to taste

> "...notching up a 93 point lead at quarter time." want to see an adjective here, like "blistering"

> "Interestingly, the Sun actually managed to win the second quarter, as the Bombers appeared to take there foot off the gas a little to only win by 139 points when all was said and done." "sun" to "suns", "there" to "their", added comma. dislike the usage of "foot off the gas a little" deeply americanised passage for a piece about australian football. find another metaphor please

> clicking a few links in this document and came across this bit of gold in the recommended from our favourite "special" comments lad over at channel seven: https://youtu.be/HpAW8IYXd7c?t=191

> "It is exciting to me that this is a game that I can remember watching on the television at the time, it may have even been the first Gold Coast game I ever watched27." "it" to "and" after the comma. this little paragraph including and after this sentence i dislike a great deal, you're illustrating the fun of football stats and the narratives thereto, you don't need to say so. i'd drop it altogether but whatever floats your boat

> "...unbelievable goals like this." still got the edit of you kicking a similar goal down the park somewhere

> "second quarter" section, 1TRUE

> "It is quite fitting (although a little sad) that the highest scoring second quarter was against a floundering (aforementioned) fitzRoy Football Club (to which we owe the ease with which we obtained this data) en-route to a wooden spoon in their final season prior to merging with Brisbane Bears to form the Brisbane Lions." couple of things - another usage of "little" in an american fashion. stop this. also you've really overdone it with the fitzroy references here, you've got a hyperlink to your earlier screed, formatted the name of the club after the r package and then an even more pointless bit of bracketed text explaining the previous two references. pick one and only one. 

> "third quarter" section, 1TRUE

> "The game on top, the Bombers had a very even distribution of goal-kickers and kicked 32 goals, so they may appear later in our list of multiple goal kickers question." add "in" after the comma, add "different" before "goal-kickers", place the number of goals before the goal kickers and reformat slightly, add a comma after all of that, take out the "multiple goal kickers question" bit and just hyperlink "later in our list" to that question if you feel it's necessary

> "all quarters" section, 1TRUE

> "Well, this was slightly unexpected, the Bloods28 came home like a freight train against the woeful Saints, in a game that took place over 100 years ago. It is also the only quarter in AFL history that has notched up a ton. Upon seeing this, given it's vintage, I though that perhaps the story of this game might have been lost to time, but the Swans have a most insightful article up on their website about it." bit of a monster paragraph but will endeavour to preserve it with minor commas (note that (haha) there are multiple additions). "its" vs. "it's" rears its ugly head again. you used "notched" in the first quarter's explanatory paragraph too, it's a unique enough word that i'd would advise changing either one (probably the former). "though" to "thought". 

> "The explanation it provides is that St Kilda were undermanned through a combination of injury and player protest on account of off-field disputes." try "the explanation provided claims" instead, bit nicer

> "In the infamous game, the Swans' third (premiership) quarter was the only one that reached the top 100 quarters of all time." usage of the word "premiership" is confusing to the casual reader (me). premiership means grand final, but this game was in round 15??? use a synonym

> "The fact that no quarter was even close to the the top indicates that the Swans were very consistent through-out the game. To use a cliche, they put in a consistent four-quarter effort and I suppose the Eagles were consistent too (consistently dismal)." torturous

> make sure to ctrl-f aforementioned and remove some of the 7 hyperlinks

> "individual" section, 1TRUE, also nice layout of the table in this section, shows you can do it if you try

> "multiple" section, 1TRUE, ditto

> "five or more (bags)" section, 1TRUE, ditto

> "Rounding out the 4 was a contribution of 5 snags..." use four instead of 4, you've been using the numeral for statistics, don't use it casually, particularly in the same sentence as a statistic

> "A clanger is defined as" and "Or in more precise football statistics terms" add colons after these

> take the full stop out of "an absurd or embarrasing blunder" and perhaps add where the definition is from, for symmetry

> "An error made by a player resulting in a negative result for his side. Disposal clangers are any kick or handball that directly turns the ball over to the opposition. Frees and 50-metre penalties against, No Pressure Errors, Dropped Marks and Debits are all included in clangers.32" quotation not formatted correctly

> "most clangers" section, 1TRUE, in the tables in this section and the next, sydney's data is highlighted with a blue background rather than red as was the case for previous tables. why?
  
  > "...rolling the dice more with possession (high risk, high reward), as popularised by Richmond..." added comma

> "Having spot-checked a few examples, there is also a bit of a pattern of wet weather impacting these games it would seem." particularly egregious example of conversational writing, it is not change that is required, but reflection

> "We will therefore have to make do with answering this question only for about the past decade." another bit that abrades the mind, "only for about" is perfectly comprehenisible when spoken, but creates a sticking point in the middle of a written sentence

> "worst disposal efficiency" section, 1TRUE

> "The only game with less than 50% disposal efficiency was played in torrid conditions up in Cairns" "torrid"'s a lovely word that unfortunately has conflicting meanings here, originating from the latin for scorch and also used to mean difficult or troubling in the modern era, you have used it in a context where it was pissing down in the late evening. change to "horrid" for a similar level of britishness

> "I have however seen equal or worse conditions in the past, so it is somewhat curious that this was the worst by such a margin." added comma

> "For reference, Gold Coast were very poor that year, coming second last but the Roos came in a respectable ninth position (only one win and percentage outside the top 8), this also points to them probably winning this game if has been played in more favourable conditions, but they still would have missed out on finals due to the mammoth percentage of the Cats that year." added commas? jeez louise put a full stop, like, somewhere. replace one of the uses of "that year". change "if has" to "if it had"

> The "cleanest" player on the day was Jesse Joyce, who's 8 touches came at 75% efficiency (however it was a rather low sample size). change "however it was" to "albeit with" and "who's" (short for who has) to "whose". apostrophes proving themselves to be tricky bastards, much like their grounded friends the commas

> "Seeing a game in 2018 is also a fun reminder of the last time the Eagles won a premiership, which feels a long way off given..." added comma

> "in spite of their recent win against the also similarly languishing35 Roos last Sunday." remove "also" from this sentence

> "In the 20th century, the use of suburban grounds where the quality of the surface was subpar I am sure lead to far more games..." change "lead" to "led". whaddya know about lead?
  
  > "when I cross referenced the games with match reports and highlights, some of the "sunny" games turned out to be played in torrential rain." added comma. would instinctually change "when i cross referenced" to "cross referencing" 

> "This has only happened 4 out of 45 times and the last time was Eagles (and Carlton) superstar Chris Judd in 2005." change "and the last time" to ", the last time being", make sure to add the comma

> "The Norm Smith Medal was first instituted in 1979. Prior to this, there was no official award given, however the media and fans of the day had their opinions of who the best on ground was in prior grand finals." added comma, would change "however" to "though"

> "He is known for a legendary moment during this match, where, towards the end of the fourth quarter, he ran down his own (errant) kick..." added comma. yes, i know there's already 3 in this sentence, and yes, you need another one

> "(father of Maurice Junior who is currently plying his trade at his old man's club)" "junior" to "jr."

> after all's said and done for our questions, would like to make a suggestion that you do some further explanation not just of the top spot on our tables, but relate those circumstances and the question at large to our "infamous game" as you like to refer to it as. bit of grounding would do this article good

> find and replace "interestingly" with synonyms, rewrite accordingly

> "...which is notable enough I think..." why would you write this

> "fitzRoy: as outlined in this article, this R package is the de facto way of sourcing AFL data." is de facto really the phrase you want to use?

> this article is way too long, auto-estimate claims 65 minutes, likely far less if you skip the code portions (as any sane person would) but still labourious. publications with a reputation for "journalistic integrity" only get away with 20 minutes maximum, what hope do you have in the age of subway surfers mmm ice cream so good yesyesyes
